# This file was generated by GoReleaser. DO NOT EDIT.
cask "becket" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "c93fb338d3e4a237941b2af8ea37fd4bc75d67efe4a4c19af0736b586379a3c2"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb9a0d188889f69b0313f1855160ce94f764ce4ac771cc911329840c747624cd"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b48f9b91414fa362256b2828a75cdb6669525b2056fd4cead8e6737083d6175c"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5286218e3029a8164f3b011131cab8045857cc5cb3b1580c9e9d14259ccd8984"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_linux_arm64.tar.gz"
    end
  end

  name "becket"
  desc "Cross-repo git-worktree workspaces"
  homepage "https://github.com/Mykhol/becket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "becket"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/becket"]
    end
  end

  # No zap stanza required

end
