# This file was generated by GoReleaser. DO NOT EDIT.
cask "becket" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "079082fa16f23d6432c4a6d65ab183cb58452f1e857d322cdf5fb233c905303c"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "914f5291d7c6e073211b15f985ca73c69e6434a15ecd5a6050550291cbedd2a0"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9074bf9d498e782ffe291b4243a68bd77c626eebd35379e2fe7f4edbc34921d4"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "712f87a3475c455c96100bc4baf6e4da3670cb845d4a81c4c2e56b1bb4551929"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_linux_arm64.tar.gz"
    end
  end

  name "becket"
  desc "Cross-repo git-worktree workspaces"
  homepage "https://github.com/Mykhol/becket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "becket"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/becket"]
    end
  end

  # No zap stanza required

end
