# This file was generated by GoReleaser. DO NOT EDIT.
cask "becket" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "bb41f5f6d5cabe24b89841ed1e4d65329625be92d91ba2ada69c6d6a91ec8689"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "397d55e50beff1ae0bd07d1daa75edd2bdbb37a8a1824064f200cbee3eed3589"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c89e7f450bf76b0a813dcd236c0b725e0237955ee70b27c16ad4e967db25d884"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e28151f048c5cfc279bd0287096367818c4d42761a906ef0ed72c1ea5c543351"
      url "https://github.com/Mykhol/becket/releases/download/v#{version}/becket_#{version}_linux_arm64.tar.gz"
    end
  end

  name "becket"
  desc "Cross-repo git-worktree workspaces"
  homepage "https://github.com/Mykhol/becket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "becket"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/becket"]
    end
  end

  # No zap stanza required

end
